### ISSUE TITLE
amplify\backend\amplify-meta.json' does not exist

### ISSUE THREAD

**Issue by datgreatkhan** [aws-amplify/amplify-hosting#3426]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1sdojde3ki6q

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

I am using Expo with React Native on Windows.

Using `amplify add auth` or `amplify update auth`, `amplify add storage` and `amplify import storage` after a `pull`, I get the following error:

```
🛑 File at path: 'C:\Users\<account name>\Documents\MyCoach\my-coach\amplify\backend\amplify-meta.json' does not exist
```

This, I assume, is what I get from virtually all `add` or `update` commands using the Amplify CLI.

Funny enough, the output from `amplify pull` (or the `amplify pull` with the `appId` and `envName` provided) tells me:

```
Successfully received Amplify Studio tokens.
Amplify AppID found: d1sdojde3ki6q. Amplify App name is: MyCoach
Backend environment staging found in Amplify Console app: MyCoach
✅ GraphQL schema compiled successfully.

Edit your schema at C:\Users\<account name>\Documents\MyCoach\my-coach\amplify\backend\api\MyCoach\schema.graphql or place .graphql files in a directory at C:\Users\<account name>\Documents\MyCoach\my-coach\amplify\backend\api\MyCoach\schema
Successfully generated models. Generated models can be found in C:\Users\<account name>\Documents\MyCoach\my-coach\app\src

✅ **Added backend environment config object to your project.**
Run 'amplify pull' to sync future upstream changes.
```

However, there is no `backend` directory at all anywhere in my project. Even with Find Files (CTRL + P) on Visual Studio, there are no results. 

### Expected behavior

I expect that it doesn't give me this error, and that it allows me to add/update `auth` properly.

Googling this issue and the suggestions were to `pull` first - which obviously doesn't work because `pull` doesn't even generate the `backend` directory or the files necessary to begin with.

This is getting frustrating especially when this issue is not well documented and this is supposed to be a "simple" thing to setup.

### Reproduction steps

1. Set up Amplify via Amplify Studio
2. Set up Authentication via Amplify Studio
3. Install Amplify CLI in root project directory (where my `node_modules`, configs, etc. are)
4. Set up Authentication on the front-end as per Amplify documentation
5. After doing `amplify pull --appId <app ID> --envName <env name>`, try doing any `amplify add` or `amplify update` commands.
6. Receive error regarding `amplify-meta.json`. Also note that no other backend related files exist, includnig `amplify.yml`

### Build Settings

```yaml
`amplify.yml` does not even exist in my project.
```

### Log output

`amplify pull`:
<details>

```
PS C:\Users\<account-name>\Documents\MyCoach\my-coach> amplify pull
Opening link: https://us-east-1.admin.amplifyapp.com/admin/d1sdojde3ki6q/staging/verify/?loginVersion=1
⠼ Confirm login in the browser or manually paste in your CLI login key:
Successfully received Amplify Studio tokens.
Backend environment staging found in Amplify Console app: MyCoach
✅ GraphQL schema compiled successfully.

Edit your schema at C:\Users\<account-name>\Documents\MyCoach\my-coach\amplify\backend\api\MyCoach\schema.graphql or place .graphql files in a directory at C:\Users\<account-name>\Documents\MyCoach\my-coach\amplify\backend\api\MyCoach\schema
Successfully generated models. Generated models can be found in C:\Users\<account-name>\Documents\MyCoach\my-coach\app\src

✅ Added backend environment config object to your project.
Run 'amplify pull' to sync future upstream changes.

```

</details>

`amplify add auth`:
<details>

```
PS C:\Users\<account-name>\Documents\MyCoach\my-coach> amplify add auth
Using service: Cognito, provided by: awscloudformation

 The current configured provider is Amazon Cognito. 

 Do you want to use the default authentication and security configuration? Default configuration with Social Provider (Federation)
 Warning: you will not be able to edit these selections.     
 How do you want users to be able to sign in? Username       
 Do you want to configure advanced settings? Yes, I want to make some additional changes.
 Warning: you will not be able to edit these selections.
 What attributes are required for signing up? Email
 Do you want to enable any of the following capabilities?
 What domain name prefix do you want to use? <domain prefix>
 Enter your redirect signin URI: http://localhost:3000/
? Do you want to add another redirect signin URI No
 Enter your redirect signout URI: http://localhost:3000/
? Do you want to add another redirect signout URI No
 Select the social providers you want to configure for your user pool: 
🛑 File at path: 'C:\Users\<account-name>\Documents\MyCoach\my-coach\amplify\backend\amplify-meta.json' does not exist
```

</details>

### Additional information

Here is my project structure:

![image](https://user-images.githubusercontent.com/129341569/231904993-7ccae559-813f-446a-8b24-55aa7fc1ffdc.png)

Here is my `.gitignore`:

![image](https://user-images.githubusercontent.com/129341569/231905095-0edd213b-6477-45d3-8c2c-ae6b3eb86650.png)

**Comment by datgreatkhan** [comment]
Fixed the issue by deleting all Amplify related files, then reinstalling and specifically saying "Yes" to the "modify/edit backend files question" with the first `amplify pull`.

My problem was on my first `amplify pull` (when setting up Amplify CLI), I did not say "Yes" to the question if I want to "modify/edit backend files". I said "no" the first time around, because it is does not inform you that it will not generate backend files. Even if you say "no", it will tell you it generated the backend stuff when it doesn't (at least for me).
